# Generated by Django 3.0.5 on 2020-05-11 12:24

from django.db import migrations, models
import referral_sample.models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_sample', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='people_invited',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='token',
            field=models.CharField(default=referral_sample.models.random_token, max_length=512),
        ),
    ]
